# PATH
export PATH="/opt/homebrew/bin:$PATH"
export PATH="$HOME/bin:$PATH"

# ENV
export ZSH_CONFIG_DIR="$HOME/.config/zsh"

# History
HISTFILE="$HOME/.cache/zsh/zsh_history"

#dont show brew hints
export HOMEBREW_NO_ENV_HINTS=1


# Plugins
PLUGINS_DIR="$ZSH_CONFIG_DIR/plugins"
function zvm_after_select_vi_mode() {
    case $ZVM_MODE in
        $ZVM_MODE_NORMAL)
            export ZVM_CUSTOM_MODE_PROMPT_CHAR="N"
        ;;
        $ZVM_MODE_INSERT)
            export ZVM_CUSTOM_MODE_PROMPT_CHAR="I"
        ;;
        $ZVM_MODE_VISUAL)
            export ZVM_CUSTOM_MODE_PROMPT_CHAR="V"
        ;;
        $ZVM_MODE_VISUAL_LINE)
            export ZVM_CUSTOM_MODE_PROMPT_CHAR="V"
        ;;
        $ZVM_MODE_REPLACE)
            export ZVM_CUSTOM_MODE_PROMPT_CHAR="R"
        ;;
    esac
    zle .reset-prompt; zle -R
}

function zvm_config() {
  ZVM_LINE_INIT_MODE=$ZVM_MODE_INSERT
}

source "$PLUGINS_DIR/zsh-autosuggestions/zsh-autosuggestions.zsh"
source "$PLUGINS_DIR/LS_COLORS/lscolors.sh"
source "$PLUGINS_DIR/zsh-vi-mode/zsh-vi-mode.plugin.zsh"

# autocomplete
autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

# load aliases
source "$ZSH_CONFIG_DIR/aliases.zsh"

# Starship
export STARSHIP_CONFIG="$ZSH_CONFIG_DIR/starship.toml"
eval "$(starship init zsh)"

